# site
site_name: Otaku101
site_domain: "otaku101.com" 
site_title: Otaku101 | Anime & Manga news
site_description: Otaku101 provides daily anime, manga, games & culture news from Japan.
site_description_footer: Otaku101 provides daily anime, manga, games & culture news from Japan. 
site_email: hello@otaku101.com

# site urls
url: "https://otaku101.com"
baseurl: "" 
permalink: :title-:year:month:day/

# pagination
pagination:
  enabled: true
  per_page: 9
  offset: 0
  limit: 0
  permalink: '/page-:num/'
  title: ':title <span>&middot;</span> Page :num of :max'
  sort_field: 'date'
  sort_reverse: true

# jekyll
strict_front_matter: true
incremental: true
plugins:
  - jekyll-autoprefixer
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate-v2
  - jekyll-sitemap
exclude:
  - .jekyll-cache
  - README.md
  - TODO.md
sass:
  sass_dir: _scss
  style: compressed
